name: Validate Code

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check C Formatting
        run: pipx run --spec clang-format==23.* clang-format -n -Werror $(find personal_simple_tcl_minifier/ -name "*.c" -o -name "*.h")

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install Validate Dependencies
        run: |
          pip install -r requirements_dev.txt
          make build-parse

      - name: Validate
        run: make validate

      - name: Unit Tests
        run: make test
